name: PTY Realtors
favicon: null
layout_spectrum: 0.1326280531939119
typography_spectrum: 0.24917
title: PTY Realtors
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#9e2929'
    - '#f4ec5c'
    - '#e8a94b'
    - '#e3673f'
  brandStrength: 0.5901443844195455
  lightness: 0.13910777098499238
  saturation: 0.11951226857490838
  rhythmicContrast: 0.7465288662351668
purpose: []
